### ISSUE TITLE
amino acid classifier error

### ISSUE THREAD

**Issue by jglees** [westlake-repl/SaprotHub#10]
When trying to classify amino acids I'm still getting the same error (despite now fixing label sequence length mismatch) 

e.g. ValueError: Expected input batch_size (1028) to match target batch_size (1480).

I've attached a file that gives an error and a file that was the gemini (AI) suggested fix...thanks

[example_fail_aa_classifier2.csv.gz](https://github.com/user-attachments/files/16019584/example_fail_aa_classifier2.csv.gz)

[gemini.txt](https://github.com/user-attachments/files/16019587/gemini.txt)

**Comment by zhikaili1150** [comment]
Hi, 

we were able to successfully run the training using your CSV dataset. 

We noticed that the Sequence in your CSV file is in SA Sequence format, so the `data_type` in section `2.1: Task Config` should be set to `Multiple SA Sequences`. Please verify this setting.

Here are some of the configurations we used to run it successfully, you can give them a try.

![example_config](https://github.com/westlake-repl/SaprotHub/assets/101766153/852a58c0-3ed7-4958-9e85-b4179e67d2cf)

**Comment by jglees** [comment]
Yes I redid the training and its working now, I must have been selecting the wrong dropdown menu or something.
Thanks !
