### ISSUE TITLE
Pairwise example prediction not working

### ISSUE THREAD

**Issue by jglees** [westlake-repl/SaprotHub#11]
I think there is an error with the pairwise classification for saprothub

using this file 
'[EXAMPLE]Multiple_pairs_of_AA_Sequences.csv'
and reading it in as

![image](https://github.com/westlake-repl/SaprotHub/assets/161373927/6d4777eb-c663-4652-b11c-0db74c6eb040)

I get the following error:

TypeError: AbstractModel.__init__() got an unexpected keyword argument 'num_labels'

thanks

**Comment by LTEnjoy** [comment]
Hi, thank you for pointing that out!

It seems that there is an error when initializing SaProt for pair classification. We will check it out and soon fix it!.

**Comment by LTEnjoy** [comment]
Hi, we have corrected the error. You can try it out now!

**Comment by jglees** [comment]
Thanks ! training  works on that now
