### ISSUE TITLE
identical sequences

### ISSUE THREAD

**Issue by QUEST2179** [westlake-repl/SaprotHub#39]
Dear developer,

pred_aa_seqs = saprot_if_model.predict(masked_aa_seq, masked_struc_seq, method=method, num_samples=num_samples)
when num_samples was set to 10, it gave 10 identical sequences. Could you please help how to generate diverse sequence? Thanks!

**Comment by LTEnjoy** [comment]
Hi, did you mask the amino acid sequence when you input it to the function? Normally the argument ``masked_aa_seq`` should be ``##########``, meaning the amino acids are masked. This function will only predict all positions that the amino acid are masked. If you input the original amino acid sequence with no mask, the outputs will also be the same as the original sequence.

**Comment by QUEST2179** [comment]
Great, my mistake, Thanks for pointing out.
