### ISSUE TITLE
Amino Acid classification training error

### ISSUE THREAD

**Issue by jglees** [westlake-repl/SaprotHub#4]
I'm trying to run amino acid classification (assigning each amino acid to one of 3 classes). But get an error at the start of training 
e.g. 
"""/usr/local/lib/python3.10/dist-packages/torch/nn/functional.py in cross_entropy(input, target, weight, size_average, ignore_index, reduce, reduction, label_smoothing)
   3084     if size_average is not None or reduce is not None:
   3085         reduction = _Reduction.legacy_get_string(size_average, reduce)
-> 3086     return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
   3087 
   3088 

ValueError: Expected input batch_size (904) to match target batch_size (906)."""

Perhaps I haven't formatted the data correctly (there is no example of a csv flatfile on the github repo for amino acid classification atm)..thanks for help!

**Comment by LTEnjoy** [comment]
Hi, 

We've provided an example that how a csv file looks like for classification task on the Colab:
![image](https://github.com/westlake-repl/SaprotHub/assets/52776915/c920a0fe-a6e7-4703-8ac2-0bdc3dd5e575)

If you don't mind, could you share your csv file to us for testing? Or you may check the format of your data to meet the requirements of input.

**Comment by jglees** [comment]
Hi,

thanks yes that one works for me,, its the one where each amino acid has a class thats failing atm,, e.g. 
MEETMKLA, "1,0,1,1,1,1,1,0", train.

I'll send an example file through
Thanks

**Comment by jglees** [comment]
[example_fail_aa_classifier.csv.gz](https://github.com/user-attachments/files/15985169/example_fail_aa_classifier.csv.gz)

**Comment by LTEnjoy** [comment]
Hi, 

We find the number of labels in each sequence is not equal to the length of sequence. It should be the same since each amino acid is assigned a label. Below is the code for reproduction:

```
import pandas as pd

csv_path = "/sujin/tmp/example_fail_aa_classifier.csv"
df = pd.read_csv(csv_path)

for i, row in df.iterrows():
    seq, label, stage = row

    # Calculate the length of the protein sequence
    seq_len = int(len(seq) / 2)
    
    # Calculate the number of labels
    num_labels = len(label.split(","))

    if seq_len != num_labels:
        print("Length of sequence and label does not match", seq_len, num_labels)

```

**Comment by jglees** [comment]
sorry I should have spotted that,,Thanks!!
